### ISSUE TITLE
MCAO config errors

### ISSUE THREAD

**Issue by VGarrel** [ANR-COMPASS/shesha#5]
Hello,

Config hardware: 
Intel i7 - 6700 @ 2.6GHz x8
Ram: 16Gb
GeForce GTX 1060
OS:
Ubuntu 16.04

The first time I tried "mcao_8m.py" was after running a prior simple SH example. The init phase resulted in a Error alloc N_actu_tot_d. 

The "mcao_8m.py" example worked after a clean reboot. Any modification from me adding one atmospheric layer results in a long series of
CUBLAS error in src.cpp/carma_cublas.cpp@410
CUBLAS error : Resource allocation failed.
CUBLAS error in src.cpp/carma_cublas.cpp@759
CUBLAS error : Resource allocation failed.
CUBLAS error in src.cpp/carma_cublas.cpp@173
CUBLAS error : Resource allocation failed.
CUBLAS error in src.cpp/carma_cublas.cpp@173
CUBLAS error : Resource allocation failed.
CUBLAS error in src.cpp/carma_cublas.cpp@210

![compass_mcao8m_alloc](https://user-images.githubusercontent.com/34507954/35215368-52b6fe5a-ff64-11e7-9e04-8fc5b02070a1.png)
![compass_mcao8m_alloc1](https://user-images.githubusercontent.com/34507954/35215409-71faf8de-ff64-11e7-8ee2-a3fb16450700.png)
![compass_mcao40m_free](https://user-images.githubusercontent.com/34507954/35215414-776e8254-ff64-11e7-8784-4267210822f1.png)

The "mcao_40m.py" crashed during the init phase with the free gpu dx_d: an illegal memory access was encountered.

My guess for these errors are related to the modest/limited amount of memory in the GTX1060 compared to more dedicated/advanced hardware? On the other side the shack-hartmann 80x80_8pix is running fine. I am not familiar with diagnostic of GPU related issues: Is there any way to know any better?
Regards,

**Comment by floferreira** [comment]
Hi,

Indeed, we have found out off-axis WFS and DM conjugated in altitude (and so MCAO cases) was not running correctly. An update has just been released to correct that, and MCAO is running correctly for us. You can find more information about this update on the website : https://anr-compass.github.io/compass/2018/01/22/debugs.html

Also, we estimate a need of 6 GB GPU memory to be able to run the MCAO 8m (>16GB for 40m) case because of the mv controller that implies computation of covariance matrices Nslopes x Nslopes and Nact x Nslopes. If you are using a GTX 1060 3 GB, it explains your problem... 
A good tip to trace bugs that occurs on the GPU is to use cuda-gdb to run your script.

I close the issue as it is resolved by the last update. Don't hesitate to open a new one if you need to.
Regards
